server:
  port: 8080
mysql:
  host: localhost
  port: 3306
  username: devuser
  password: PhucDZ@2004!
  database: myapp
logger:
  level: debug
  maxsize: 5
  maxbackup: 3
  maxage: 28
  compress: true
  filepath: "./storage/log_xxx.log"